export const list = [
  {
    id: "12345678",
    title: "Cтатья",
    categories: "МАИ/Факультет/Кафедра",
    creator: "Никита",
    creation_date: "21.09.2020",
    text: "qwertyhjm",
  },
  {
    id: "sadfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "12345fg678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "sadfdfgdfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
];
