export const list = [
  {
    id: "12345678",
    title: "Cтатья",
    categories: "МАИ/Факультет/Кафедра",
    creator: "Никита",
    creation_date: "21.09.2020",
    text: "qwertyhjm",
  },
  {
    id: "sadfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "12345fg678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "sadfdfgdfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghsdfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "12345dfgdf678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "sadssdfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghfdgfgdgs",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "12345ujuyhg678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "sadfhkhjkgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghffdfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "123456ghgfh78",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "sadfsdfsgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghsdgsfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "123sdgd45678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "shgadfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "jghuufds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "1234567uu8",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "sauufgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    id: "uujghfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
];
