export const list = [
  {
    uuid: "12345678",
    title: "Cтатья",
    categories: "МАИ/Факультет/Кафедра",
    creator: "Никита",
    creation_date: "21.09.2020",
    text: "qwertyhjm",
  },
  {
    uuid: "sadfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "jghfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "12345fg678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "sadfdfgdfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "jghsdfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "12345dfgdf678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "sadssdfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "jghfdgfgdgs",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "12345ujuyhg678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "sadfhkhjkgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "jghffdfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "123456ghgfh78",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "sadfsdfsgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "jghsdgsfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "123sdgd45678",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "shgadfgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "jghuufds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "1234567uu8",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "sauufgh",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
  {
    uuid: "uujghfds",
    title: "1",
    categories: "1/2",
    creator: "123",
    creation_date: "234",
    text: "qwertyhjm",
  },
];
